version: '2'

services:
  serviio:
    image: riftbit/docker-serviio:latest
    ports:
     - "23423:23423/tcp"
     - "8895:8895/tcp"
     - "1900:1900/udp"
    volumes:
     - $librarypath:/opt/serviio/library
     - $pluginspath:/opt/serviio/plugins
     - $logpath:/opt/serviio/log
